/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package calenderapplication;

import java.awt.event.MouseEvent;
import java.util.Calendar;

/**
 *
 * @author Subodh Joshi
 */
public class PopupWindow extends javax.swing.JFrame {

    /**
     * Creates new form PopupWindow
     */
    public PopupWindow(Controller ce) {
        initComponents();
        c=ce;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel3.setBackground(new java.awt.Color(50, 48, 48));

        jPanel1.setBackground(new java.awt.Color(50, 48, 48));
        jPanel1.setLayout(new java.awt.GridLayout(2, 3));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 204, 204));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Day");
        jPanel1.add(jLabel1);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 204, 204));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Month");
        jPanel1.add(jLabel4);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 204, 204));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Year");
        jPanel1.add(jLabel2);

        Calendar ce=Calendar.getInstance();
        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 204, 204));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        if(ce.getTime().getDate()<10)
        jLabel3.setText("0"+ce.getTime().getDate());
        else
        jLabel3.setText(ce.getTime().getDate()+"");
        jLabel3.addMouseWheelListener(new java.awt.event.MouseWheelListener() {
            public void mouseWheelMoved(java.awt.event.MouseWheelEvent evt) {
                jLabel3MouseWheelMoved(evt);
            }
        });
        jPanel1.add(jLabel3);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 204, 204));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        int O=ce.getTime().getMonth()+1;
        String O1=null;
        if(O==1)
        O1="Jan";
        if(O==2)
        O1="Feb";
        if(O==3)
        O1="Mar";
        if(O==4)
        O1="Apr";
        if(O==5)
        O1="May";
        if(O==6)
        O1="Jun";
        if(O==7)
        O1="Jul";
        if(O==8)
        O1="Aug";
        if(O==9)
        O1="Sep";
        if(O==10)
        O1="Oct";
        if(O==11)
        O1="Nov";
        if(O==12)
        O1="Dec";
        jLabel5.setText(O1);
        jLabel5.addMouseWheelListener(new java.awt.event.MouseWheelListener() {
            public void mouseWheelMoved(java.awt.event.MouseWheelEvent evt) {
                jLabel5MouseWheelMoved(evt);
            }
        });
        jPanel1.add(jLabel5);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 204, 204));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText(ce.getTime().getYear()-100+2000+"");
        jLabel6.addMouseWheelListener(new java.awt.event.MouseWheelListener() {
            public void mouseWheelMoved(java.awt.event.MouseWheelEvent evt) {
                jLabel6MouseWheelMoved(evt);
            }
        });
        jPanel1.add(jLabel6);

        jPanel2.setBackground(new java.awt.Color(50, 48, 48));
        jPanel2.setLayout(new java.awt.GridLayout(1, 2));

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 204, 204));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("OK");
        jLabel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 204)));
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel8);

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 204, 204));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("CANCEL");
        jLabel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 204)));
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel9);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel3MouseWheelMoved(java.awt.event.MouseWheelEvent evt) {//GEN-FIRST:event_jLabel3MouseWheelMoved
        // TODO add your handling code here:
        int d=Integer.parseInt(jLabel3.getText());
        int y=Integer.parseInt(jLabel6.getText());
        String m=jLabel5.getText();
        if(evt.getWheelRotation()>0)
        {
            d=d+1;
            if((m.equals("Jan"))&&d==32)
            {
                d=1;
                jLabel5.setText("Feb");
            }
            if((m.equals("Feb"))&&d>28)
            {
                leap l=new leap();
                int flag=l.Leap(y);
                if(((flag==0)&&(d==29))||((flag==1)&&(d==30))){
                    d=1;
                    jLabel5.setText("Mar");
                }
            }
            if((m.equals("Mar"))&&d==32)
            {
                d=1;
                jLabel5.setText("Apr");
            }
            if((m.equals("Apr"))&&d==31)
            {
                d=1;
                jLabel5.setText("May");
            }
            if((m.equals("May"))&&d==32)
            {
                d=1;
                jLabel5.setText("Jun");
            }
            if((m.equals("Jun"))&&d==31)
            {
                d=1;
                jLabel5.setText("Jul");
            }
            if((m.equals("Jul"))&&d==32)
            {
                d=1;
                jLabel5.setText("Aug");
            }
            if((m.equals("Aug"))&&d==32)
            {
                d=1;
                jLabel5.setText("Sep");
            }
            if((m.equals("Sep"))&&d==31)
            {
                d=1;
                jLabel5.setText("Oct");
            }
            if((m.equals("Oct"))&&d==32)
            {
                d=1;
                jLabel5.setText("Nov");
            }
            if((m.equals("Nov"))&&d==31)
            {
                d=1;
                jLabel5.setText("Dec");
            }
            if((m.equals("Dec"))&&d==32)
            {
                d=1;
                jLabel5.setText("Jan");
                y=y+1;
                jLabel6.setText(y+"");
            }
            if(d<10)
            jLabel3.setText("0"+d);
            else
            jLabel3.setText(d+"");
           
        }
        else{
              d=d-1;
            if((m.equals("Jan"))&&d==0)
            {
                d=31;
                jLabel5.setText("Dec");
                y=y-1;
                jLabel6.setText(y+"");
            }
            if((m.equals("Feb"))&&d==0)
            {
                d=31;
                jLabel5.setText("Jan");
            }
            if((m.equals("Mar"))&&d==0)
            {
                leap l=new leap();
                int flag=l.Leap(y);
                if(flag==1)
                d=29;
                else
                d=28;
                jLabel5.setText("Feb");
            }
            if((m.equals("Apr"))&&d==0)
            {
                d=31;
                jLabel5.setText("Mar");
            }
            if((m.equals("May"))&&d==0)
            {
                d=30;
                jLabel5.setText("Apr");
            }
            if((m.equals("Jun"))&&d==0)
            {
                d=31;
                jLabel5.setText("May");
            }
            if((m.equals("Jul"))&&d==0)
            {
                d=30;
                jLabel5.setText("Jun");
            }
            if((m.equals("Aug"))&&d==0)
            {
                d=31;
                jLabel5.setText("Jul");
            }
            if((m.equals("Sep"))&&d==0)
            {
                d=31;
                jLabel5.setText("Aug");
            }
            if((m.equals("Oct"))&&d==0)
            {
                d=30;
                jLabel5.setText("Sep");
            }
            if((m.equals("Nov"))&&d==0)
            {
                d=31;
                jLabel5.setText("Oct");
            }
            if((m.equals("Dec"))&&d==0)
            {
                d=30;
                jLabel5.setText("Nov");
            }
            if(d<10)
            jLabel3.setText("0"+d);
            else
            jLabel3.setText(d+"");
        }
    }//GEN-LAST:event_jLabel3MouseWheelMoved

    private void jLabel5MouseWheelMoved(java.awt.event.MouseWheelEvent evt) {//GEN-FIRST:event_jLabel5MouseWheelMoved
        // TODO add your handling code here:
        String mo=jLabel5.getText();
        int d=Integer.parseInt(jLabel3.getText());
        int y=Integer.parseInt(jLabel6.getText());
        if(evt.getWheelRotation()>0)
        {
            leap l=new leap();
            int flag=l.Leap(y);
            if("Jan".equals(mo))
            {
                if(d>28&&flag==0)
                d=28;
                if(d>29&&flag==1)
                d=29;
                jLabel5.setText("Feb");
                if(d>10)
                jLabel3.setText(d+"");
                else
                jLabel3.setText("0"+d);
            }
            if("Feb".equals(mo))
            {
                jLabel5.setText("Mar");
            }
            if("Mar".equals(mo))
            {
                if(d==31)
                d=30;
                jLabel5.setText("Apr");
                if(d>10)
                jLabel3.setText(d+"");
                else
                jLabel3.setText("0"+d);
            }
            if("Apr".equals(mo))
            {
                jLabel5.setText("May");
            }
            if("May".equals(mo))
            {
                if(d==31)
                d=30;
                jLabel5.setText("Jun");
                if(d>10)
                jLabel3.setText(d+"");
                else
                jLabel3.setText("0"+d);
            }
            if("Jun".equals(mo))
            {
                jLabel5.setText("Jul");
            }
            if("Jul".equals(mo))
            {
                jLabel5.setText("Aug");
            }
            if("Aug".equals(mo))
            {
                if(d==31)
                d=30;
                jLabel5.setText("Sep");
                if(d>10)
                jLabel3.setText(d+"");
                else
                jLabel3.setText("0"+d);
            }
            if("Sep".equals(mo))
            {
                jLabel5.setText("Oct");
            }
            if("Oct".equals(mo))
            {
                if(d==31)
                d=30;
                jLabel5.setText("Nov");
                if(d>10)
                jLabel3.setText(d+"");
                else
                jLabel3.setText("0"+d);
            }
            if("Nov".equals(mo))
            {
                jLabel5.setText("Dec");
            }
            if("Dec".equals(mo))
            {
                y=y+1;
                jLabel6.setText(y+"");
                jLabel5.setText("Jan");
            }
        }
        else{
            leap l=new leap();
            int flag=l.Leap(y);
            if("Jan".equals(mo))
            {
                y=y-1;
                jLabel6.setText(y+"");
                jLabel5.setText("Dec");
            }
            if("Feb".equals(mo))
            {
                jLabel5.setText("Jan");
            }
            if("Mar".equals(mo))
            {
                d=Integer.parseInt(jLabel3.getText());
                if((d>28)&&(flag==0))
                {
                    d=28;
                }
                if((d>29)&&(flag==1))
                {
                    d=29;
                }
                if(d>10)
                jLabel3.setText(d+"");
                else
                jLabel3.setText("0"+d);
                jLabel5.setText("Feb");
            }
            if("Apr".equals(mo))
            {
                jLabel5.setText("Mar");
            }
            if("May".equals(mo))
            {
                if(d==31)
                d=30;
                if(d>10)
                jLabel3.setText(d+"");
                else
                jLabel3.setText("0"+d);
                jLabel5.setText("Apr");
            }
            if("Jun".equals(mo))
            {
                jLabel5.setText("May");
            }
            if("Jul".equals(mo))
            {
                if(d==31)
                d=30;
                if(d>10)
                jLabel3.setText(d+"");
                else
                jLabel3.setText("0"+d);
                jLabel5.setText("Jun");
            }
            if("Aug".equals(mo))
            {
                jLabel5.setText("Jul");
            }
            if("Sep".equals(mo))
            {
                jLabel5.setText("Aug");
            }
            if("Oct".equals(mo))
            {
                if(d==31)
                d=30;
                if(d>10)
                jLabel3.setText(d+"");
                else
                jLabel3.setText("0"+d);
                jLabel5.setText("Sep");
            }
            if("Nov".equals(mo))
            jLabel5.setText("Oct");
            if("Dec".equals(mo))
            {
                if(d==31)
                d=30;
                if(d>10)
                jLabel3.setText(d+"");
                else
                jLabel3.setText("0"+d);
                jLabel5.setText("Nov");
            }
        }
    }//GEN-LAST:event_jLabel5MouseWheelMoved

    private void jLabel6MouseWheelMoved(java.awt.event.MouseWheelEvent evt) {//GEN-FIRST:event_jLabel6MouseWheelMoved
        // TODO add your handling code here:
        int y=Integer.parseInt(jLabel6.getText());
        String mo=jLabel5.getText();
        int d=Integer.parseInt(jLabel3.getText());
        if(evt.getWheelRotation()>0)
        {
            y=y+1;
            leap l=new leap();
            int flag=l.Leap(y);
            if(mo.equals("Feb"))
            {
                if((flag==0)&&(d>28))
                d=28;
                if((flag==1)&&(d>29))
                d=29;
                jLabel3.setText(d+"");
            }
            jLabel6.setText(y+"");
        }
        else{
            y=y-1;
            leap l=new leap();
            int flag=l.Leap(y);
            if(mo.equals("Feb"))
            {
                if((flag==0)&&(d>28))
                d=28;
                if((flag==1)&&(d>29))
                d=29;
                jLabel3.setText(d+"");
            }

            jLabel6.setText(y+"");

       }
    }//GEN-LAST:event_jLabel6MouseWheelMoved

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        // TODO add your handling code here:
        int day=Integer.parseInt(jLabel3.getText());
        String m=jLabel5.getText();
        int year=Integer.parseInt(jLabel6.getText());
        int month = 0;
        if(m=="Jan")
        month=1;
        if(m=="Feb")
        month=2;
        if(m=="Mar")
        month=3;
        if(m=="Apr")
        month=4;
        if(m=="May")
        month=5;
        if(m=="Jun")
        month=6;
        if(m=="Jul")
        month=7;
        if(m=="Aug")
        month=8;
        if(m=="Sep")
        month=9;
        if(m=="Oct")
        month=10;
        if(m=="Nov")
        month=11;
        if(m=="Dec")
        month=12;
        c.setMonthYear( month, year);
        MouseEvent arg0 = null; 
        c.Button(arg0, month, year);
        this.dispose();

    }//GEN-LAST:event_jLabel8MouseClicked

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jLabel9MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PopupWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PopupWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PopupWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PopupWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               // new PopupWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
    public Controller c;
}
